all_data <- read.table('household_power_consumption.txt', sep=";", na.strings="?", header=TRUE)
needed_dates <- c('1/2/2007', '2/2/2007')
useful_data <- subset(all_data,all_data$Date==needed_dates[1]|all_data$Date==needed_dates[2])
png(file="plot3.png", width = 480, height = 480)
dates_data<-strptime(paste(useful_data$Date, useful_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
plot(dates_data,useful_data$Sub_metering_1, type = "s", ylab="Energy sub metering", xlab="", col="black")
points(dates_data,useful_data$Sub_metering_2, type = "s" , col="red")
points(dates_data,useful_data$Sub_metering_3, type = "s", ylab="Global Active Power (kilowatts)", xlab="", col="blue")
legend('topright',legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)
dev.off()